language: php

php:
  - '5.6'
  - '7.2'

services:
  - mysql

before_script:
  - cp app/config/parameters_travis.yml app/config/parameters.yml
  - composer install
  - php bin/console doctrine:database:create --env=test
  - php bin/console doctrine:schema:create --env=test

script:
  - phpunit

notifications:
  email:

notifications:
  email:
    recipients:
      - jeremie.samson76@gmail.com
    on_success: [never]
    on_failure: [always]