<?php

namespace AppBundle\Repository;

/**
 * EmailAlertRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EmailAlertRepository extends \Doctrine\ORM\EntityRepository
{
}
