<?php

namespace AppBundle\Repository;

/**
 * MangaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MangaRepository extends \Doctrine\ORM\EntityRepository
{
}
