services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    AppBundle\:
        resource: '../../src/AppBundle/*'
        exclude: '../../src/AppBundle/{Entity,Repository,Tests}'

    AppBundle\Controller\:
        resource: '../../src/AppBundle/Controller'
        public: true
        tags: ['controller.service_arguments']

    scraper:
        class:     AppBundle\Service\Scraper
        arguments: ['%scantrad_manga_url%']
        public: true

    email_alert_info:
        class:     AppBundle\Service\EmailAlertInfo
        arguments: ['@doctrine.orm.entity_manager']
        public: true